### ISSUE TITLE
does this theme work with php 8.3 and gravcms 1.7.46

### ISSUE THREAD

**Issue by joebordes** [getgrav/grav-theme-woo#17]
I updated PHP 8.3 and gravcms 1.7.46. The site is giving two errors

waypoints.js jquery error which I fixed by updating waypoints to the latest version

jquery.3-x TypeError: url.indexOf is not a function
    at jQuery.fn.load (jquery-3.x.min.js:10194:13)
    at main.js:12:14
    at main.js:247:3

I tried updating jquery also but the error just switches lines

any help appreciated

**Comment by joebordes** [comment]
I added this code:

```diff
jquery-3.x.js  line 10190
/**
 * Load a url into a page
 */
jQuery.fn.load = function( url, params, callback ) {
+	if (typeof url=='function') {
+		return url();
+	}
	var selector, type, response,
		self = this,
		off = url.indexOf( " " );
```

and the page loads now, the HTML is messed up, due to the twig raw change
HTH

**Comment by joebordes** [comment]
```
TypeError: sections.waypoint is not a function
    at main.js:94:11
    at main.js:247:3
```

**Comment by joebordes** [comment]
can't get imagelightbox working :-/

**Comment by robertgarrigos** [comment]
this [PR](/getgrav/grav-theme-woo/pull/19) fixes this.

**Comment by joebordes** [comment]
Thanks!  I'll give it a try when I can and let you know.
